---
title: "Assignment 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(tidyverse)
library(readr)
```

```{r}
url <- read_html("https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=01.01.2018&datoTil=07.10.2018&id_region=100&id_fylke=19&id_kommune=-+-+-&id_niva1=51&id_niva2=-+-+-&id_bransje1=0")

#Henter tabell fra siden, dette fant jeg ut var nummer 4
Tvang <- html_table(html_nodes(url, "table")[[4]], fill=TRUE)

tail(Tvang)
#Ser at kolonner etter kolonne 8 er bare verdier av "NA"

#Tar ut bare de kolonnene vi trenger som er alle fra og med 2 til og med 8
Tvang <- Tvang[2:8]
```

```{r}
#Fjerner tomme kolonner
Tvang <- Tvang[-2]
Tvang <- Tvang[-3]
Tvang <- Tvang[-4]

#Fjerner tomme rekker
Tvang <- Tvang[!apply(Tvang == "", 1, all),]

#Fjerner også de 2 øverste ettersom vi ikke trenger disse
Tvang <- Tvang[-1:-2,]
#Retter på nummerering av rekkene
rownames(Tvang) <- c(1:271)

#Endrer kolonnenavn
colnames(Tvang)[1:4] <- c("Bedrift", "Bedrift_nummer", "Dato", "Type")

#Fjerner hvite mellomrom i bedriftsnummer og setter det som numeric
Tvang$Bedrift_nummer <- str_replace_all(string= Tvang$Bedrift_nummer, pattern=" ", repl="")
Tvang$Bedrift_nummer <- as.numeric(Tvang$Bedrift_nummer)

#Endrer type dato
Tvang$Dato <- as.Date(Tvang$Dato, #%d.%m.%Y)
```

```{r}
#Filtrere ut personer, dette kan gjøres gjennom filtrering under bedriftsnummer, der det står fødselsdatoen til personen istedenfor bedriftsnummer
Tvang <- Tvang %>%
  filter(nchar(Bedrift_nummer) > 6)

#Tar så å filtrerer slik at vi bare har de med Tvangsoppløsning
Tvangsoppløsning <- Tvang %>%
  filter(Type == "Tvangsoppløsning")
```

```{r}
ggplot() +
  geom_bar(data = Tvang, aes (Type)) +
  labs(title = "Hvor stor andel av sakene er Tvangsoppløsning", x = "Type", y = "Antall") 
```

